import type { Metadata } from 'next'
import './globals.scss'
import 'atropos/css'
import 'tippy.js/dist/tippy.css'
import { Header } from '@/components/Header'
import { Footer } from '@/components/molecules/Footer'
import Loader from '@/components/atoms/Loader'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white font-inter">
        <Loader />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
