import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/Header'
import { ReactLenis } from '@/components/libs/lenis'
import { Footer } from '@/components/molecules/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white font-inter">
        <ReactLenis root>
          <Header />
          {children}
          <Footer />
        </ReactLenis>
      </body>
    </html>
  )
}
